# Generated by Django 2.2.7 on 2019-11-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EloMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Иконка'),
        ),
    ]
