# Generated by Django 2.2.7 on 2019-11-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("EloMain", "0003_auto_20191108_0901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="championship",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="championship",
                to="EloMain.Championship",
                verbose_name="Чемпионат",
            ),
        ),
    ]
