# Generated by Django 2.0.6 on 2019-11-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EloMain', '0008_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='club_1',
            field=models.CharField(max_length=50, verbose_name='1-е место'),
        ),
        migrations.AlterField(
            model_name='position',
            name='club_10',
            field=models.CharField(max_length=50, verbose_name='10-е место'),
        ),
        migrations.AlterField(
            model_name='position',
            name='club_2',
            field=models.CharField(max_length=50, verbose_name='2-е место'),
        ),
        migrations.AlterField(
            model_name='position',
            name='club_3',
            field=models.CharField(max_length=50, verbose_name='3-е место'),
        ),
        migrations.AlterField(
            model_name='position',
            name='club_4',
            field=models.CharField(max_length=50, verbose_name='4-е место'),
        ),
        migrations.AlterField(
            model_name='position',
            name='club_5',
            field=models.CharField(max_length=50, verbose_name='5-е место'),
        ),
        migrations.AlterField(
            model_name='position',
            name='club_6',
            field=models.CharField(max_length=50, verbose_name='6-е место'),
        ),
        migrations.AlterField(
            model_name='position',
            name='club_7',
            field=models.CharField(max_length=50, verbose_name='7-е место'),
        ),
        migrations.AlterField(
            model_name='position',
            name='club_8',
            field=models.CharField(max_length=50, verbose_name='8-е место'),
        ),
        migrations.AlterField(
            model_name='position',
            name='club_9',
            field=models.CharField(max_length=50, verbose_name='9-е место'),
        ),
    ]
