# Generated by Django 2.2.7 on 2020-02-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EloMain', '0014_auto_20191212_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='logo',
        ),
    ]
