# Generated by Django 2.2.7 on 2020-05-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EloMain', '0016_remove_championship_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя опции')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции приложения',
                'db_table': 'options',
            },
        ),
    ]
